Home task #5, v.1
idunskiy/ProjectDjango pull request #1
Opened 2020-04-29 14:27 UTC by idunskiy

2020-04-30 10:50 UTC, dbradul requested changes
Пожалуйста, удалите `.idea` и `env` из репозитория. Я не могу найти ваши изменения.

2020-05-01 10:58 UTC, dbradul requested changes

2020-05-01 10:58 UTC, dbradul commented on .gitignore
> +.idea/
Радикально! .gitignore на все случаи жизни)

2020-05-01 10:58 UTC, dbradul commented on .idea/workspace.xml
> +    <list default="true" id="70db2cae-8ca5-4510-9a9e-9bd07da0eaa2" name="Default Changelist" comment="">
но папка `.idea` по-прежнему не удалена.
`.gitignore` работает только для еще неотслеживаемых файлов и папок. Если файл уже был добавлен в гит, его надо явно удалить.

2020-05-01 10:58 UTC, dbradul commented on src/test_app/views.py
> +ROOT_DIR = "/Users/ivan/PythonProjects/ProjectDjango/src/test_app"
Есть возможность получить корень Django-проекта из `settings.py`
```
from django.conf import settings
...
print(settings.BASE_DIR)
```

2020-05-01 11:03 UTC, idunskiy commented on .idea/workspace.xml
> +    <list default="true" id="70db2cae-8ca5-4510-9a9e-9bd07da0eaa2" name="Default Changelist" comment="">
Хм, а как не удалена, если ее нет в ветке dev?
https://github.com/idunskiy/ProjectDjango/tree/dev

2020-05-03 10:37 UTC, merged